name: Deploy Flask App

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Docker
        run: |
          which docker
          docker --version
          docker compose version

      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose up -d --pull always
