#this is a workflow
name: Hello workflow

#runs on a trigger 
on:
  push:
    branches:
      - main
#these are jobs under the workflow
jobs:
 #name pf the jobs/steps
  greet:
    #this is a github runner, each jobs run on a runner
    runs-on: ubuntu-latest   #github server
    steps:
      - name: Say hello to jobs
        run: echo "Hello Dosto"

      - name: Say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python, docker, etc
        run: docker --version && python --version

